services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
        # Los puertos serán insertados automáticamente aquí
    devices:
      - '/dev/ttyS3:/dev/ttyS3' # Maps COM3 to container
    environment:
      DATABASE_URL: mysql://root:ugelpassword@db_container_name:3306/mesa_ayuda
    networks:
      - shared_network
    privileged: true # May be needed for serial port access

networks:
  shared_network:
    external: true
